title: AI-OWLS
subtitle: Advancing Cutting-edge AI through Innovative Optimization, Efficient Model Engineering, and Distributed Systems Design
logo: /assets/img/AI-OWLS_logo.png
description: Open-source ML/AI algorithms research at Rice CS
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
