title: AI-OWLS 
subtitle: Advancing Cutting-edge AI through Innovative Optimization, Efficient Model Engineering, and Distributed Systems Design
logo: /assets/img/AI-OWLS_logo.png
description: Supported by Ken Kennedy Institute (Rice University)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
