title: AI-OWLS 
subtitle: AI-OWLS: Advancing Cutting-edge AI through Innovative Optimization, Efficient Model Engineering, and Distributed Systems Design
logo: /assets/img/AI-OWLS_logo.png
description: Supported by K2I Rice
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
